language: java
jdk:
  - oraclejdk8

os:
  - linux
dist: trusty

addons:
  firefox: "50.0"

before_install:
  #load all submodules
  - git submodule init
  - git submodule update
  #update all repo lists
  - sudo apt-get update -y
  #install curl for tomcat tests
  - sudo apt-get install curl -y
  # get thrift 0.9.3
  - wget "https://www.dropbox.com/s/u4prfzehb94xo9n/thrift"
  - wget "https://www.dropbox.com/s/ydbf9ghsl6lv5dl/libthrift-0.9.3.jar"
  - chmod 755 thrift
  - sudo cp thrift /usr/local/bin/thrift
  - sudo cp libthrift-0.9.3.jar /usr/local/lib
  # get checkstyle
  - wget http://downloads.sourceforge.net/project/checkstyle/checkstyle/7.0/checkstyle-7.0-all.jar
  #fake random with urandom (do not repeat it on your own computer)
  - sudo rm /dev/random
  - sudo mknod /dev/random c 1 9
  # for gui tests
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

install:
  #install and run tests
  - mvn install -P travis
  - cd UI-testing
  - mvn install -DskipTests
  - cd ..

script:
  #run checkstyle
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml auth-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml dashboard-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml editor-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml db-services/db-diagram-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml db-services/db-robot-store-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml db-services/db-user-service/src
  - java -jar checkstyle-7.0-all.jar -c Travis/checkstyle/checkstyle.xml UI-testing/src

  #run services
  - cd db-services

  - cd db-diagram-service
  - mvn exec:java -P travis &
  - sleep 15

  - cd ../db-user-service
  - mvn exec:java -P travis &
  - sleep 15

  - cd ../db-robot-store-service
  - mvn exec:java -P travis &
  - sleep 15

  - cd ../../auth-service
  - mvn tomcat7:run-war-only -P travis &
  - sleep 30

  - cd  ../dashboard-service
  - mvn tomcat7:run-war-only -P travis &
  - sleep 30

  - cd ../editor-service
  - mvn tomcat7:run-war-only -P travis &
  - sleep 30

  - ../Travis/callTomcat.sh

  - cd ../UI-testing
  - mvn test -P travis &
  - sleep 60

notifications:
  slack: qreal-web:sT5qgA4qZZ9eyLI0yy2Mp81E
